sudo: false
language: node_js
node_js:
- 0.12.7
script:
- make -f .travis test
notifications:
  slack:
    secure: auzL6SRHDlP96z79c9C8LtLLbmDrg0SaTSrTK8osQvmnXdKB7V3G+aqyNp6JPbejpvix8C+xkzkeaLra75cNjFntEHclLzbipFZuP++8zQzNMw6MrtEiGJd5+orTsizoheI1TUKPtp9pkJqJ5Q2lWOb4AEjkmemnHN3v4zyidtc=
  webhooks: https://api.integrator.io/v1/exports/55ed3cc386de45f94413d3e0/data
